
#created on: Feb 4, 2009
package mx.ecosur.multigame.manantiales

import mx.ecosur.multigame.GameState;
import mx.ecosur.multigame.MessageSender;

import mx.ecosur.multigame.Color;

import mx.ecosur.multigame.ejb.entity.Cell;
import mx.ecosur.multigame.ejb.entity.Game;
import mx.ecosur.multigame.ejb.entity.GameGrid;
import mx.ecosur.multigame.ejb.entity.GamePlayer;
import mx.ecosur.multigame.ejb.entity.Move;
import mx.ecosur.multigame.ejb.entity.Move.*;

import mx.ecosur.multigame.ejb.entity.manantiales.Ficha;
import mx.ecosur.multigame.ejb.entity.manantiales.ManantialesMove;

import mx.ecosur.multigame.manantiales.HardConstraint;
import mx.ecosur.multigame.manantiales.CheckConstraint;

import java.util.List;

/*
    Determines if the destination of the requested move is
    empty on the grid.
*/
function boolean isEmpty (GameGrid grid, ManantialesMove move) {
    Cell destination = move.getDestination();
    Cell current = grid.getLocation (destination);
    boolean ret = (current == null);
    if (!ret)
        move.setStatus (Status.INVALID);
    return ret;
}

#Sets the players in the game so that Black has the first turn
rule "setup"
    agenda-group "initialize"
when
    game : Game (state == GameState.BEGIN);
then
    List<GamePlayer> players = game.getPlayers();
    for (GamePlayer p : players) {
        if (p.getColor() == Color.YELLOW)
            p.setTurn(true);
        else
            p.setTurn(false);
    }
    GameGrid grid = new GameGrid ();
    modify (game) { setGrid (grid), setState (GameState.PLAY), setPlayers (players) } 
    MessageSender messageSender = new MessageSender();
    messageSender.sendPlayerChange(game);
    messageSender.sendStartGame(game);
end

rule "evaluate-move"
    agenda-group "verify"
when
    game  : Game (state == GameState.PLAY, $grid : grid)
    move  : ManantialesMove (status == Status.UNVERIFIED, player.turn == true)
    eval (isEmpty (game.getGrid(), move))   
then
    modify (move) { setStatus (Status.VERIFIED) }
end   

# Executes a simple move
rule "execute-move"
    agenda-group "move"
when 
    game  : Game (state == GameState.PLAY)
    move  : ManantialesMove (player.turn == true, status == Status.VERIFIED)  
then
    #Modify gamegrid 
    GameGrid modifiedGrid = game.getGrid();   
    modifiedGrid.updateCell (move.getDestination());
    modify (move) { setStatus (Status.MOVED) }
    modify (game) { setGrid (modifiedGrid) }
    MessageSender messageSender = new MessageSender();
    messageSender.sendMoveComplete(move);
end
