/*
* Copyright (C) 2010 ECOSUR, Andrew Waterman and Max Pimm
*
* Licensed under the Academic Free License v. 3.0.
* http://www.opensource.org/licenses/afl-3.0.php
*/

/**
 * This rule package creates a strategic, "Random" player.  The Random player
 * reads the board, looking for any open moves that fulfill the following
 * requirements:
 *
 *   a.  Can connect to another piece the same color as this player
 *   b.  Or can connect to another piece the same color as this player's partner.
 * A randomizer is used to choose from moves that satisfy the above requirements.
 * If no possible moves can be found, then the Random player will place a token
 * randomly, adjacent to a cell of the opposition's colors.
 *
 * @author awaterma@ecosur.mx
*/

package mx.ecosur.multigame.impl.entity.gente;

import mx.ecosur.multigame.enums.GameState;
import mx.ecosur.multigame.grid.model.GridCell;
import mx.ecosur.multigame.grid.Color;

import java.util.HashSet;
import java.util.TreeSet;
import java.util.Random;

#Yellow must move first, and that move can only be at the center of the board
rule "first-move"
    lock-on-active true
when
    game   : GenteGame (state == GameState.PLAY, $grid : grid)
    player : GenteStrategyAgent (turn == true, color == Color.YELLOW, nextMove==null)
    eval ($grid.isEmpty())
then
    GenteMove centerMove = new GenteMove (player, new GridCell (
        game.getRows() / 2, game.getColumns () / 2, player.getColor()));
    modify (player) { setNextMove (centerMove) }
end

rule "random-move"
    lock-on-active true
    salience -10
when
    game   : GenteGame (state == GameState.PLAY, $grid : grid)
    player : GenteStrategyAgent (turn == true, nextMove == null)
    eval (!$grid.isEmpty())
then
    GenteMove nextMove = null;
    TreeSet<GenteMove> possible = player.determineAvailableMoves(game);
    if (possible.size() == 0)
        possible = player.determineAvailableMoves (game,
            player.oppositionColors());
    Random random = new Random ();
    for (GenteMove move : possible) {
        if (random.nextBoolean()) {
            nextMove = move;
            break;
        }
    }
    if (nextMove == null) {
        for (GenteMove move : possible) {
            nextMove = move;
            break;
         }
    }
    modify (player) { setNextMove (nextMove) }
end